# Generated by Django 5.2.13 on 2026-04-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Symbol",
            fields=[
                (
                    "symbol",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("sector", models.CharField(blank=True, default="", max_length=64)),
                ("first_seen", models.DateField(blank=True, null=True)),
                ("last_seen", models.DateField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "dim_symbols",
                "ordering": ["symbol"],
            },
        ),
        migrations.CreateModel(
            name="RawFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("mkt_rf", models.FloatField(null=True)),
                ("smb", models.FloatField(null=True)),
                ("hml", models.FloatField(null=True)),
                ("rmw", models.FloatField(null=True)),
                ("cma", models.FloatField(null=True)),
                ("mom", models.FloatField(null=True)),
                ("rf", models.FloatField(null=True)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("source", models.CharField(default="ken_french_5f", max_length=64)),
            ],
            options={
                "db_table": "raw_factors",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "source"), name="raw_factors_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RawPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=16)),
                ("date", models.DateField(db_index=True)),
                ("open", models.FloatField(null=True)),
                ("high", models.FloatField(null=True)),
                ("low", models.FloatField(null=True)),
                ("close", models.FloatField(null=True)),
                ("adj_close", models.FloatField(null=True)),
                ("volume", models.BigIntegerField(null=True)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("source", models.CharField(default="yfinance", max_length=32)),
            ],
            options={
                "db_table": "raw_prices",
                "indexes": [models.Index(fields=["date"], name="raw_prices_date_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("symbol", "date", "source"), name="raw_prices_uniq"
                    )
                ],
            },
        ),
    ]
