# Generated by Django 5.2.13 on 2026-04-24 21:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DqRun",
            fields=[
                (
                    "run_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("summary", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "dq_runs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="DqCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_name", models.CharField(db_index=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[("pass", "pass"), ("warn", "warn"), ("fail", "fail")],
                        db_index=True,
                        max_length=8,
                    ),
                ),
                ("rows_checked", models.BigIntegerField(default=0)),
                ("rows_failed", models.BigIntegerField(default=0)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("ts", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="quality.dqrun",
                    ),
                ),
            ],
            options={
                "db_table": "dq_checks",
                "ordering": ["-ts"],
            },
        ),
    ]
