# Generated by Django 5.2.13 on 2026-04-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RfPortfolioReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_id", models.UUIDField(db_index=True)),
                ("date", models.DateField(db_index=True)),
                ("strategy_return", models.FloatField()),
            ],
            options={
                "db_table": "rf_portfolio_returns",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run_id", "date"), name="rf_port_ret_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RfPortfolioWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_id", models.UUIDField(db_index=True)),
                ("rebalance_date", models.DateField(db_index=True)),
                ("symbol", models.CharField(max_length=16)),
                ("weight", models.FloatField()),
            ],
            options={
                "db_table": "rf_portfolio_weights",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run_id", "rebalance_date", "symbol"),
                        name="rf_port_wt_uniq",
                    )
                ],
            },
        ),
    ]
