# Generated by Django 5.2.13 on 2026-04-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FctFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=16)),
                ("date", models.DateField(db_index=True)),
                ("rsi", models.FloatField(null=True)),
                ("garman_klass_volatility", models.FloatField(null=True)),
                ("close_over_open", models.FloatField(null=True)),
                ("atr", models.FloatField(null=True)),
                ("macd", models.FloatField(null=True)),
                ("bb_low", models.FloatField(null=True)),
                ("bb_mid", models.FloatField(null=True)),
                ("bb_high", models.FloatField(null=True)),
                ("return_1m", models.FloatField(null=True)),
                ("return_2m", models.FloatField(null=True)),
                ("return_3m", models.FloatField(null=True)),
                ("return_6m", models.FloatField(null=True)),
                ("return_9m", models.FloatField(null=True)),
                ("return_12m", models.FloatField(null=True)),
                ("beta_mkt_rf", models.FloatField(null=True)),
                ("beta_smb", models.FloatField(null=True)),
                ("beta_hml", models.FloatField(null=True)),
                ("beta_rmw", models.FloatField(null=True)),
                ("beta_cma", models.FloatField(null=True)),
                ("target_1m", models.FloatField(null=True)),
                ("built_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "fct_features",
                "indexes": [
                    models.Index(fields=["date"], name="fct_features_date_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("symbol", "date"), name="fct_features_uniq"
                    )
                ],
            },
        ),
    ]
