# Generated by Django 5.2.13 on 2026-04-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RfPick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_id", models.UUIDField(db_index=True)),
                ("rebalance_date", models.DateField(db_index=True)),
                ("symbol", models.CharField(max_length=16)),
                ("y_pred", models.FloatField()),
                ("picked_rank", models.IntegerField()),
                ("target_1m", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "rf_picks",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run_id", "rebalance_date", "symbol"),
                        name="rf_pick_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RfPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_id", models.UUIDField(db_index=True)),
                ("rebalance_date", models.DateField(db_index=True)),
                ("symbol", models.CharField(db_index=True, max_length=16)),
                ("y_pred", models.FloatField()),
                ("rank", models.IntegerField()),
            ],
            options={
                "db_table": "rf_predictions",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run_id", "rebalance_date", "symbol"),
                        name="rf_pred_uniq",
                    )
                ],
            },
        ),
    ]
