# Generated by Django 5.2.13 on 2026-04-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_rf", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rfpick",
            name="direction",
            field=models.SmallIntegerField(
                choices=[(1, "long"), (-1, "short")], default=1
            ),
        ),
    ]
