# Generated by Django 5.2.13 on 2026-04-24 21:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Experiment",
            fields=[
                ("experiment_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "experiment",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "run_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "running"),
                            ("completed", "completed"),
                            ("failed", "failed"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(db_index=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("git_sha", models.CharField(blank=True, default="", max_length=40)),
                ("error", models.TextField(blank=True, default="")),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="tracker_core.experiment",
                    ),
                ),
            ],
            options={
                "db_table": "run",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="RunArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("path", models.CharField(max_length=512)),
                ("kind", models.CharField(blank=True, default="", max_length=32)),
                ("size_bytes", models.BigIntegerField(default=0)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="tracker_core.run",
                    ),
                ),
            ],
            options={
                "db_table": "run_artifact",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "name"), name="run_artifact_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RunFeatureImportance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature", models.CharField(db_index=True, max_length=128)),
                ("importance", models.FloatField()),
                ("rank", models.IntegerField(default=0)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_importances",
                        to="tracker_core.run",
                    ),
                ),
            ],
            options={
                "db_table": "run_feature_importance",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "feature"), name="run_feat_imp_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RunMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=128)),
                ("value", models.FloatField()),
                ("step", models.IntegerField(default=0)),
                ("ts", models.DateTimeField()),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="tracker_core.run",
                    ),
                ),
            ],
            options={
                "db_table": "run_metric",
                "indexes": [
                    models.Index(fields=["run", "key"], name="run_metric_run_key_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="RunParam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=128)),
                ("value_json", models.TextField()),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="params",
                        to="tracker_core.run",
                    ),
                ),
            ],
            options={
                "db_table": "run_param",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "key"), name="run_param_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RunTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(db_index=True, max_length=64)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="tracker_core.run",
                    ),
                ),
            ],
            options={
                "db_table": "run_tag",
                "constraints": [
                    models.UniqueConstraint(fields=("run", "tag"), name="run_tag_uniq")
                ],
            },
        ),
    ]
